### PR TITLE
added typescript

### PR DESCRIPTION
**Pull request by Niryo**
@Dor256 , I got this failure while trying to build files, so I reverted and created the pr again:
```
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
child_process.js:644
    throw err;
    ^

Error: Command failed: find . -not \( -path ./node_modules -prune \)  -not \( -path ./.idea -prune \)  -type f  -name '*.kompot.*.js' -or -name '*.kompot.*.ts
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at getAllFilesWithKompotExtension (/Users/niryo/git/wix-one-app-platform/node_modules/kompot/src/scripts/generateIndex.js:112:39)
    at Object.<anonymous> (/Users/niryo/git/wix-one-app-platform/node_modules/kompot/src/scripts/generateIndex.js:33:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

### CODE REVIEW

**Comment by Dor256** [comment]
I see the problem, pushing a fix

**Comment by Niryo** [comment]
also, do we need to publish the tsconfig file? If so, add it to the files prop

**Comment by Dor256** [comment]
I don't believe we need it thats why I left it out, if you feel we should add it then it's not problem

**Comment by Dor256** [comment]
Getting access denied for some reason...

**Comment by Dor256** [comment]
Ran a check inside new login module - works like a charm!
I added some minor type changes that I noticed were missing.

**Comment by Niryo** [comment]
ok, i will check it tonight and merge it

**Pull request merged**
